# eureka client
eureka:
  instance:
    # Random port 기반의 동적으로 생성되는 각 Instance를 구분하기 위한 Instance ID 설정
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true # fetch-registry 속성 : Eureka 서버로부터 인스턴스들의 정보를 가져올것인지에 대한 여부 설정 항목
    service-url: # service-url 속성 : eureka server의 위치 정보를 설정하는 항목
      defaultZone: http://127.0.0.1:8761/eureka

---
# actuator for bus-refresh and prometheus metrics
management:
  endpoints:
    web:
      exposure:
        include: busrefresh

---
spring:
  # rabbitmq for spring-cloud-bus
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: admin
    password: admin

  # zipkin for distributed tracing
  zipkin:
    base-url: http://localhost:9411

  #sletuh for distributed tracing
  sleuth:
    sampler:
      probability: 1.0

