spring:
  zipkin:
    base-url: http://localhost:9411

  sleuth:
    sampler:
      probability: 1.0

  # add p6syp-configurations bean to sleuth-zipkin
  main:
    allow-bean-definition-overriding: true